name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}  # Puedes omitir si es 21
          local-dir: ./
          server-dir: /htdocs
