name: 🚀 Deploy a Netlify

on:
  push:
    paths:
      - 'netlify/**'
      - 'common/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🧩 Copiar assets compartidos a Netlify
        run: |
          mkdir -p netlify/assets
          cp -r common/assets/* netlify/assets/

      - name: 📦 Instalar Netlify CLI
        run: npm install -g netlify-cli

      - name: 🚀 Hacer deploy a Netlify
        run: netlify deploy --dir=netlify --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
