name: 🚀 Deploy a InfinityFree

on:
  push:
    paths:
      - 'infinityfree/**'
      - 'common/**'
  workflow_dispatch:  # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🧩 Copiar archivos compartidos a InfinityFree
        run: |
          mkdir -p infinityfree/assets
          cp -r common/* infinityfree/assets/

      - name: 📤 Subir archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./infinityfree/
          server-dir: /hsn-token.social-networking.me/htdocs/
