name: Deploy to InfinityFree

on:
  push:
    paths:
      - 'infinityfree/**'
      - 'common/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy shared assets to infinityfree
        run: |
          mkdir -p infinityfree/assets
          cp -r common/* infinityfree/assets/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./infinityfree/
          server-dir: /htdocs/
